
package mailClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "mailService", targetNamespace = "http://MailWebSer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://MailWebSer/", className = "mailClient.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://MailWebSer/", className = "mailClient.SendEmailResponse")
    @Action(input = "http://MailWebSer/mailService/sendEmailRequest", output = "http://MailWebSer/mailService/sendEmailResponse")
    public boolean sendEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://MailWebSer/", className = "mailClient.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://MailWebSer/", className = "mailClient.SendEmailBatchResponse")
    @Action(input = "http://MailWebSer/mailService/sendEmailBatchRequest", output = "http://MailWebSer/mailService/sendEmailBatchResponse")
    public boolean sendEmailBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vaildateEmail", targetNamespace = "http://MailWebSer/", className = "mailClient.VaildateEmail")
    @ResponseWrapper(localName = "vaildateEmailResponse", targetNamespace = "http://MailWebSer/", className = "mailClient.VaildateEmailResponse")
    @Action(input = "http://MailWebSer/mailService/vaildateEmailRequest", output = "http://MailWebSer/mailService/vaildateEmailResponse")
    public boolean vaildateEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
