
package mailClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "mailServiceService", targetNamespace = "http://MailWebSer/", wsdlLocation = "http://localhost:9090/Service/mailService?wsdl")
public class MailServiceService
    extends Service
{

    private final static URL MAILSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILSERVICESERVICE_EXCEPTION;
    private final static QName MAILSERVICESERVICE_QNAME = new QName("http://MailWebSer/", "mailServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/Service/mailService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAILSERVICESERVICE_WSDL_LOCATION = url;
        MAILSERVICESERVICE_EXCEPTION = e;
    }

    public MailServiceService() {
        super(__getWsdlLocation(), MAILSERVICESERVICE_QNAME);
    }

    public MailServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILSERVICESERVICE_QNAME, features);
    }

    public MailServiceService(URL wsdlLocation) {
        super(wsdlLocation, MAILSERVICESERVICE_QNAME);
    }

    public MailServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILSERVICESERVICE_QNAME, features);
    }

    public MailServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MailService
     */
    @WebEndpoint(name = "mailServicePort")
    public MailService getMailServicePort() {
        return super.getPort(new QName("http://MailWebSer/", "mailServicePort"), MailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailService
     */
    @WebEndpoint(name = "mailServicePort")
    public MailService getMailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MailWebSer/", "mailServicePort"), MailService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILSERVICESERVICE_EXCEPTION!= null) {
            throw MAILSERVICESERVICE_EXCEPTION;
        }
        return MAILSERVICESERVICE_WSDL_LOCATION;
    }

}
